--- #YAML:1.0
name:                       Labyrinth-Plugin-Articles-Diary
version:                    1.05
abstract:                   Diary plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  perl:                     5.006
  Labyrinth:                5.27
  Labyrinth::Plugin::Core:  5.17
  Clone:                    0
  Time::Local:              0
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.70

provides:
  Labyrinth::Plugin::Articles::Diary:
    file:     lib/Labyrinth/Plugin/Articles/Diary.pm
    version:  1.05

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  homepage:   http://labyrinth.missbarbell.co.uk
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Articles-Diary
  repository: http://github.com/barbie/labyrinth-plugin-articles-diary

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
